ALTER TABLE eg_incident_v2 ADD COLUMN district CHARACTER VARYING(256);
ALTER TABLE eg_incident_v2 ADD COLUMN block CHARACTER VARYING(256);
ALTER TABLE eg_incident_v2 ADD COLUMN phctype CHARACTER VARYING(256);
ALTER TABLE eg_incident_v2 ADD COLUMN phcsubtype CHARACTER VARYING(256);
ALTER TABLE eg_incident_v2 ADD COLUMN incidentsubtype CHARACTER VARYING(256);

DROP TABLE IF EXISTS eg_incident_address_v2;